### ISSUE TITLE
Diaper + Cheat Bug

### ISSUE THREAD

**Issue by IAmTheHighGround** [OmoExplorer/long-hour-and-a-half#18]
Neither diapers nor pads stop/absorb the flow of pee 
Pressing the cheat button in v1.3 crashes the game

**Comment by utkinn** [comment]
Diapers and pads will absorb pee on wetting in the next update.

**Comment by IAmTheHighGround** [comment]
Diapers still do not work in 1.3.1
Or perhaps you mean they will be implemented in 1.4

**Comment by utkinn** [comment]
For now they absorb the pee when the pee holding ability is 0 and character is leaking.
They will also work when bladder level is very high in update v1.4.

**Comment by utkinn** [comment]
Because diaper and pads aren't fully implemented for now, this issue should be opened​.
